// <auto-generated />
using System;
using MareSynchronosShared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MareSynchronosServer.Migrations
{
    [DbContext(typeof(MareDbContext))]
    [Migration("20260425104230_RemoveCharacterRpProfileIconId")]
    partial class RemoveCharacterRpProfileIconId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MareSynchronosShared.Models.Auth", b =>
                {
                    b.Property<string>("HashedKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hashed_key");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<string>("PrimaryUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("primary_user_uid");

                    b.Property<string>("UserUID")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.HasKey("HashedKey")
                        .HasName("pk_auth");

                    b.HasIndex("PrimaryUserUID")
                        .HasDatabaseName("ix_auth_primary_user_uid");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_auth_user_uid");

                    b.ToTable("auth", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.AutoDetectSchedule", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.PrimitiveCollection<int[]>("ActiveWeekdays")
                        .HasColumnType("integer[]")
                        .HasColumnName("active_weekdays");

                    b.Property<int?>("DisplayDurationHours")
                        .HasColumnType("integer")
                        .HasColumnName("display_duration_hours");

                    b.Property<DateTime?>("LastActivatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activated_utc");

                    b.Property<bool>("Recurring")
                        .HasColumnType("boolean")
                        .HasColumnName("recurring");

                    b.Property<string>("TimeEndLocal")
                        .HasColumnType("text")
                        .HasColumnName("time_end_local");

                    b.Property<string>("TimeStartLocal")
                        .HasColumnType("text")
                        .HasColumnName("time_start_local");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.HasKey("GroupGID")
                        .HasName("pk_autodetect_schedules");

                    b.ToTable("autodetect_schedules", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.Banned", b =>
                {
                    b.Property<string>("CharacterIdentification")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("character_identification");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.HasKey("CharacterIdentification")
                        .HasName("pk_banned_users");

                    b.ToTable("banned_users", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.BannedRegistrations", b =>
                {
                    b.Property<string>("DiscordIdOrLodestoneAuth")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("discord_id_or_lodestone_auth");

                    b.HasKey("DiscordIdOrLodestoneAuth")
                        .HasName("pk_banned_registrations");

                    b.ToTable("banned_registrations", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("UploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uploader_uid");

                    b.Property<int>("AccessType")
                        .HasColumnType("integer")
                        .HasColumnName("access_type");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("CustomizeData")
                        .HasColumnType("text")
                        .HasColumnName("customize_data");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer")
                        .HasColumnName("download_count");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<string>("GlamourerData")
                        .HasColumnType("text")
                        .HasColumnName("glamourer_data");

                    b.Property<string>("ManipulationData")
                        .HasColumnType("text")
                        .HasColumnName("manipulation_data");

                    b.Property<int>("ShareType")
                        .HasColumnType("integer")
                        .HasColumnName("share_type");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id", "UploaderUID")
                        .HasName("pk_chara_data");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_chara_data_id");

                    b.HasIndex("UploaderUID")
                        .HasDatabaseName("ix_chara_data_uploader_uid");

                    b.ToTable("chara_data", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataAllowance", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedGroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("allowed_group_gid");

                    b.Property<string>("AllowedUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("allowed_user_uid");

                    b.HasKey("ParentId", "ParentUploaderUID", "Id")
                        .HasName("pk_chara_data_allowance");

                    b.HasIndex("AllowedGroupGID")
                        .HasDatabaseName("ix_chara_data_allowance_allowed_group_gid");

                    b.HasIndex("AllowedUserUID")
                        .HasDatabaseName("ix_chara_data_allowance_allowed_user_uid");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_allowance_parent_id");

                    b.ToTable("chara_data_allowance", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataFile", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<string>("GamePath")
                        .HasColumnType("text")
                        .HasColumnName("game_path");

                    b.Property<string>("FileCacheHash")
                        .IsRequired()
                        .HasColumnType("character varying(40)")
                        .HasColumnName("file_cache_hash");

                    b.HasKey("ParentId", "ParentUploaderUID", "GamePath")
                        .HasName("pk_chara_data_files");

                    b.HasIndex("FileCacheHash")
                        .HasDatabaseName("ix_chara_data_files_file_cache_hash");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_files_parent_id");

                    b.ToTable("chara_data_files", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataFileSwap", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<string>("GamePath")
                        .HasColumnType("text")
                        .HasColumnName("game_path");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.HasKey("ParentId", "ParentUploaderUID", "GamePath")
                        .HasName("pk_chara_data_file_swaps");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_file_swaps_parent_id");

                    b.ToTable("chara_data_file_swaps", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataOriginalFile", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<string>("GamePath")
                        .HasColumnType("text")
                        .HasColumnName("game_path");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.HasKey("ParentId", "ParentUploaderUID", "GamePath")
                        .HasName("pk_chara_data_orig_files");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_orig_files_parent_id");

                    b.ToTable("chara_data_orig_files", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataPose", b =>
                {
                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parent_id");

                    b.Property<string>("ParentUploaderUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("parent_uploader_uid");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("PoseData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pose_data");

                    b.Property<string>("WorldData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("world_data");

                    b.HasKey("ParentId", "ParentUploaderUID", "Id")
                        .HasName("pk_chara_data_poses");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_chara_data_poses_parent_id");

                    b.ToTable("chara_data_poses", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharacterRpProfileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterName")
                        .HasColumnType("text")
                        .HasColumnName("character_name");

                    b.Property<int>("ChatIcon")
                        .HasColumnType("integer")
                        .HasColumnName("chat_icon");

                    b.Property<bool>("IsRpNSFW")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rp_nsfw");

                    b.Property<string>("MoodlesData")
                        .HasColumnType("text")
                        .HasColumnName("moodles_data");

                    b.Property<string>("RpAdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("rp_additional_info");

                    b.Property<string>("RpAffiliation")
                        .HasColumnType("text")
                        .HasColumnName("rp_affiliation");

                    b.Property<string>("RpAge")
                        .HasColumnType("text")
                        .HasColumnName("rp_age");

                    b.Property<string>("RpAlignment")
                        .HasColumnType("text")
                        .HasColumnName("rp_alignment");

                    b.Property<string>("RpBuild")
                        .HasColumnType("text")
                        .HasColumnName("rp_build");

                    b.Property<string>("RpCustomFields")
                        .HasColumnType("text")
                        .HasColumnName("rp_custom_fields");

                    b.Property<string>("RpDescription")
                        .HasColumnType("text")
                        .HasColumnName("rp_description");

                    b.Property<string>("RpEthnicity")
                        .HasColumnType("text")
                        .HasColumnName("rp_ethnicity");

                    b.Property<string>("RpFirstName")
                        .HasColumnType("text")
                        .HasColumnName("rp_first_name");

                    b.Property<string>("RpHeight")
                        .HasColumnType("text")
                        .HasColumnName("rp_height");

                    b.Property<string>("RpLastName")
                        .HasColumnType("text")
                        .HasColumnName("rp_last_name");

                    b.Property<string>("RpNameColor")
                        .HasColumnType("text")
                        .HasColumnName("rp_name_color");

                    b.Property<string>("RpOccupation")
                        .HasColumnType("text")
                        .HasColumnName("rp_occupation");

                    b.Property<string>("RpProfilePictureBase64")
                        .HasColumnType("text")
                        .HasColumnName("rp_profile_picture_base64");

                    b.Property<string>("RpRace")
                        .HasColumnType("text")
                        .HasColumnName("rp_race");

                    b.Property<string>("RpResidence")
                        .HasColumnType("text")
                        .HasColumnName("rp_residence");

                    b.Property<string>("RpTitle")
                        .HasColumnType("text")
                        .HasColumnName("rp_title");

                    b.Property<string>("UserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<long>("WorldId")
                        .HasColumnType("bigint")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_character_rp_profiles");

                    b.HasIndex("UserUID", "CharacterName", "WorldId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_rp_profiles_user_uid_character_name_world_id");

                    b.ToTable("character_rp_profiles", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.ClientPair", b =>
                {
                    b.Property<string>("UserUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<string>("OtherUserUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("other_user_uid");

                    b.Property<bool>("AllowReceivingMessages")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_receiving_messages");

                    b.Property<bool>("DisableAnimations")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_animations");

                    b.Property<bool>("DisableSounds")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_sounds");

                    b.Property<bool>("DisableVFX")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_vfx");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.HasKey("UserUID", "OtherUserUID")
                        .HasName("pk_client_pairs");

                    b.HasIndex("OtherUserUID")
                        .HasDatabaseName("ix_client_pairs_other_user_uid");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_client_pairs_user_uid");

                    b.ToTable("client_pairs", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.Establishment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BannerImageBase64")
                        .HasColumnType("text")
                        .HasColumnName("banner_image_base64");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long?>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("division_id");

                    b.Property<string>("FactionTag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("faction_tag");

                    b.Property<bool?>("IsApartment")
                        .HasColumnType("boolean")
                        .HasColumnName("is_apartment");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.PrimitiveCollection<string[]>("Languages")
                        .HasColumnType("text[]")
                        .HasColumnName("languages");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer")
                        .HasColumnName("location_type");

                    b.Property<string>("LogoImageBase64")
                        .HasColumnType("text")
                        .HasColumnName("logo_image_base64");

                    b.Property<int?>("ManagerRpProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_rp_profile_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerUID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_uid");

                    b.Property<long?>("PlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("plot_id");

                    b.Property<float?>("Radius")
                        .HasColumnType("real")
                        .HasColumnName("radius");

                    b.Property<long?>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<string>("Schedule")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("schedule");

                    b.Property<decimal?>("ServerId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("server_id");

                    b.Property<bool>("ShowManagerOnProfile")
                        .HasColumnType("boolean")
                        .HasColumnName("show_manager_on_profile");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<long>("TerritoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("territory_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<long?>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("ward_id");

                    b.Property<float?>("X")
                        .HasColumnType("real")
                        .HasColumnName("x");

                    b.Property<float?>("Y")
                        .HasColumnType("real")
                        .HasColumnName("y");

                    b.Property<float?>("Z")
                        .HasColumnType("real")
                        .HasColumnName("z");

                    b.HasKey("Id")
                        .HasName("pk_establishments");

                    b.HasIndex("ManagerRpProfileId")
                        .HasDatabaseName("ix_establishments_manager_rp_profile_id");

                    b.HasIndex("OwnerUID")
                        .HasDatabaseName("ix_establishments_owner_uid");

                    b.HasIndex("TerritoryId", "LocationType")
                        .HasDatabaseName("ix_establishments_territory_id_location_type");

                    b.ToTable("establishments", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.EstablishmentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at_utc");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("establishment_id");

                    b.Property<int>("Recurrence")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_establishment_events");

                    b.HasIndex("EstablishmentId")
                        .HasDatabaseName("ix_establishment_events_establishment_id");

                    b.ToTable("establishment_events", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.FileCache", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hash");

                    b.Property<bool>("S3Confirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("s3confirmed");

                    b.Property<DateTime?>("S3ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("s3confirmed_at");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("upload_date");

                    b.Property<bool>("Uploaded")
                        .HasColumnType("boolean")
                        .HasColumnName("uploaded");

                    b.Property<string>("UploaderUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uploader_uid");

                    b.HasKey("Hash")
                        .HasName("pk_file_caches");

                    b.HasIndex("S3Confirmed")
                        .HasDatabaseName("ix_file_caches_s3confirmed");

                    b.HasIndex("UploaderUID")
                        .HasDatabaseName("ix_file_caches_uploader_uid");

                    b.ToTable("file_caches", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.ForbiddenUploadEntry", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("hash");

                    b.Property<string>("ForbiddenBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("forbidden_by");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.HasKey("Hash")
                        .HasName("pk_forbidden_upload_entries");

                    b.ToTable("forbidden_upload_entries", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.Group", b =>
                {
                    b.Property<string>("GID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gid");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alias");

                    b.Property<bool>("AutoDetectVisible")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_detect_visible");

                    b.Property<bool>("DisableAnimations")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_animations");

                    b.Property<bool>("DisableSounds")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_sounds");

                    b.Property<bool>("DisableVFX")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_vfx");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("InvitesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("invites_enabled");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_temporary");

                    b.Property<int>("MaxUserCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_user_count");

                    b.Property<string>("OwnerUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_uid");

                    b.Property<bool>("PasswordTemporarilyDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("password_temporarily_disabled");

                    b.HasKey("GID")
                        .HasName("pk_groups");

                    b.HasIndex("OwnerUID")
                        .HasDatabaseName("ix_groups_owner_uid");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.GroupBan", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<string>("BannedUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("banned_user_uid");

                    b.Property<string>("BannedByUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("banned_by_uid");

                    b.Property<DateTime>("BannedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_on");

                    b.Property<string>("BannedReason")
                        .HasColumnType("text")
                        .HasColumnName("banned_reason");

                    b.HasKey("GroupGID", "BannedUserUID")
                        .HasName("pk_group_bans");

                    b.HasIndex("BannedByUID")
                        .HasDatabaseName("ix_group_bans_banned_by_uid");

                    b.HasIndex("BannedUserUID")
                        .HasDatabaseName("ix_group_bans_banned_user_uid");

                    b.HasIndex("GroupGID")
                        .HasDatabaseName("ix_group_bans_group_gid");

                    b.ToTable("group_bans", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.GroupPair", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<string>("GroupUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("group_user_uid");

                    b.Property<bool>("CanPlacePings")
                        .HasColumnType("boolean")
                        .HasColumnName("can_place_pings");

                    b.Property<bool>("DisableAnimations")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_animations");

                    b.Property<bool>("DisableSounds")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_sounds");

                    b.Property<bool>("DisableVFX")
                        .HasColumnType("boolean")
                        .HasColumnName("disable_vfx");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_moderator");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("boolean")
                        .HasColumnName("is_paused");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.HasKey("GroupGID", "GroupUserUID")
                        .HasName("pk_group_pairs");

                    b.HasIndex("GroupGID")
                        .HasDatabaseName("ix_group_pairs_group_gid");

                    b.HasIndex("GroupUserUID")
                        .HasDatabaseName("ix_group_pairs_group_user_uid");

                    b.ToTable("group_pairs", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.GroupProfile", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<string>("Base64BannerImage")
                        .HasColumnType("text")
                        .HasColumnName("base64banner_image");

                    b.Property<string>("Base64ProfileImage")
                        .HasColumnType("text")
                        .HasColumnName("base64profile_image");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_disabled");

                    b.Property<bool>("IsNSFW")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nsfw");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("GroupGID")
                        .HasName("pk_group_profiles");

                    b.ToTable("group_profiles", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.GroupTempInvite", b =>
                {
                    b.Property<string>("GroupGID")
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<string>("Invite")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("invite");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.HasKey("GroupGID", "Invite")
                        .HasName("pk_group_temp_invites");

                    b.HasIndex("GroupGID")
                        .HasDatabaseName("ix_group_temp_invites_group_gid");

                    b.HasIndex("Invite")
                        .HasDatabaseName("ix_group_temp_invites_invite");

                    b.ToTable("group_temp_invites", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.HousingShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("CipherData")
                        .HasColumnType("bytea")
                        .HasColumnName("cipher_data");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("division_id");

                    b.Property<long>("HouseId")
                        .HasColumnType("bigint")
                        .HasColumnName("house_id");

                    b.Property<long>("MapId")
                        .HasColumnType("bigint")
                        .HasColumnName("map_id");

                    b.Property<byte[]>("Nonce")
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<string>("OwnerUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_uid");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<byte[]>("Tag")
                        .HasColumnType("bytea")
                        .HasColumnName("tag");

                    b.Property<long>("TerritoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("territory_id");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("ward_id");

                    b.HasKey("Id")
                        .HasName("pk_housing_shares");

                    b.HasIndex("OwnerUID")
                        .HasDatabaseName("ix_housing_shares_owner_uid");

                    b.HasIndex("ServerId", "TerritoryId", "DivisionId", "WardId", "HouseId")
                        .HasDatabaseName("ix_housing_shares_server_id_territory_id_division_id_ward_id_h");

                    b.ToTable("housing_shares", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.HousingShareAllowedGroup", b =>
                {
                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.Property<string>("AllowedGroupGid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("allowed_group_gid");

                    b.HasKey("ShareId", "AllowedGroupGid")
                        .HasName("pk_housing_share_allowed_groups");

                    b.HasIndex("AllowedGroupGid")
                        .HasDatabaseName("ix_housing_share_allowed_groups_allowed_group_gid");

                    b.ToTable("housing_share_allowed_groups", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.HousingShareAllowedUser", b =>
                {
                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.Property<string>("AllowedIndividualUid")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("allowed_individual_uid");

                    b.HasKey("ShareId", "AllowedIndividualUid")
                        .HasName("pk_housing_share_allowed_users");

                    b.HasIndex("AllowedIndividualUid")
                        .HasDatabaseName("ix_housing_share_allowed_users_allowed_individual_uid");

                    b.ToTable("housing_share_allowed_users", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.LodeStoneAuth", b =>
                {
                    b.Property<decimal>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_id");

                    b.Property<string>("HashedLodestoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hashed_lodestone_id");

                    b.Property<string>("LodestoneAuthString")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lodestone_auth_string");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("UserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.HasKey("DiscordId")
                        .HasName("pk_lodestone_auth");

                    b.HasIndex("UserUID")
                        .HasDatabaseName("ix_lodestone_auth_user_uid");

                    b.ToTable("lodestone_auth", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.McdfShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("CipherData")
                        .HasColumnType("bytea")
                        .HasColumnName("cipher_data");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer")
                        .HasColumnName("download_count");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<byte[]>("Nonce")
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<string>("OwnerUID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("owner_uid");

                    b.Property<byte[]>("Salt")
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<byte[]>("Tag")
                        .HasColumnType("bytea")
                        .HasColumnName("tag");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id")
                        .HasName("pk_mcdf_shares");

                    b.HasIndex("OwnerUID")
                        .HasDatabaseName("ix_mcdf_shares_owner_uid");

                    b.ToTable("mcdf_shares", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.McdfShareAllowedGroup", b =>
                {
                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.Property<string>("AllowedGroupGid")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("allowed_group_gid");

                    b.HasKey("ShareId", "AllowedGroupGid")
                        .HasName("pk_mcdf_share_allowed_groups");

                    b.HasIndex("AllowedGroupGid")
                        .HasDatabaseName("ix_mcdf_share_allowed_groups_allowed_group_gid");

                    b.ToTable("mcdf_share_allowed_groups", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.McdfShareAllowedUser", b =>
                {
                    b.Property<Guid>("ShareId")
                        .HasColumnType("uuid")
                        .HasColumnName("share_id");

                    b.Property<string>("AllowedIndividualUid")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("allowed_individual_uid");

                    b.HasKey("ShareId", "AllowedIndividualUid")
                        .HasName("pk_mcdf_share_allowed_users");

                    b.HasIndex("AllowedIndividualUid")
                        .HasDatabaseName("ix_mcdf_share_allowed_users_allowed_individual_uid");

                    b.ToTable("mcdf_share_allowed_users", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.Slot", b =>
                {
                    b.Property<Guid>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<long>("DivisionId")
                        .HasColumnType("bigint")
                        .HasColumnName("division_id");

                    b.Property<string>("GroupGID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("group_gid");

                    b.Property<long>("PlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("plot_id");

                    b.Property<float>("Radius")
                        .HasColumnType("real")
                        .HasColumnName("radius");

                    b.Property<long>("ServerId")
                        .HasColumnType("bigint")
                        .HasColumnName("server_id");

                    b.Property<string>("SlotDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("slot_description");

                    b.Property<string>("SlotName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slot_name");

                    b.Property<long>("TerritoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("territory_id");

                    b.Property<long>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("ward_id");

                    b.Property<float>("X")
                        .HasColumnType("real")
                        .HasColumnName("x");

                    b.Property<float>("Y")
                        .HasColumnType("real")
                        .HasColumnName("y");

                    b.Property<float>("Z")
                        .HasColumnType("real")
                        .HasColumnName("z");

                    b.HasKey("SlotId")
                        .HasName("pk_slots");

                    b.HasIndex("GroupGID")
                        .HasDatabaseName("ix_slots_group_gid");

                    b.HasIndex("ServerId", "TerritoryId", "WardId", "PlotId")
                        .HasDatabaseName("ix_slots_server_id_territory_id_ward_id_plot_id");

                    b.ToTable("slots", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.User", b =>
                {
                    b.Property<string>("UID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("uid");

                    b.Property<string>("Alias")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("alias");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("boolean")
                        .HasColumnName("is_moderator");

                    b.Property<DateTime>("LastLoggedIn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_logged_in");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea")
                        .HasColumnName("timestamp");

                    b.HasKey("UID")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.UserProfileData", b =>
                {
                    b.Property<string>("UserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<string>("Base64ProfileImage")
                        .HasColumnType("text")
                        .HasColumnName("base64profile_image");

                    b.Property<bool>("FlaggedForReport")
                        .HasColumnType("boolean")
                        .HasColumnName("flagged_for_report");

                    b.Property<bool>("IsNSFW")
                        .HasColumnType("boolean")
                        .HasColumnName("is_nsfw");

                    b.Property<bool>("ProfileDisabled")
                        .HasColumnType("boolean")
                        .HasColumnName("profile_disabled");

                    b.Property<string>("UserDescription")
                        .HasColumnType("text")
                        .HasColumnName("user_description");

                    b.HasKey("UserUID")
                        .HasName("pk_user_profile_data");

                    b.ToTable("user_profile_data", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.UserProfileDataReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("report_date");

                    b.Property<string>("ReportReason")
                        .HasColumnType("text")
                        .HasColumnName("report_reason");

                    b.Property<string>("ReportedUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reported_user_uid");

                    b.Property<string>("ReportingUserUID")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("reporting_user_uid");

                    b.HasKey("Id")
                        .HasName("pk_user_profile_data_reports");

                    b.HasIndex("ReportedUserUID")
                        .HasDatabaseName("ix_user_profile_data_reports_reported_user_uid");

                    b.HasIndex("ReportingUserUID")
                        .HasDatabaseName("ix_user_profile_data_reports_reporting_user_uid");

                    b.ToTable("user_profile_data_reports", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.WildRpAnnouncement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("character_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("Message")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message");

                    b.Property<int?>("RpProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("rp_profile_id");

                    b.Property<long>("TerritoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("territory_id");

                    b.Property<string>("UserUID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("user_uid");

                    b.Property<long?>("WardId")
                        .HasColumnType("bigint")
                        .HasColumnName("ward_id");

                    b.Property<long>("WorldId")
                        .HasColumnType("bigint")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_wild_rp_announcements");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("ix_wild_rp_announcements_expires_at_utc");

                    b.HasIndex("RpProfileId")
                        .HasDatabaseName("ix_wild_rp_announcements_rp_profile_id");

                    b.HasIndex("UserUID")
                        .IsUnique()
                        .HasDatabaseName("ix_wild_rp_announcements_user_uid");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_wild_rp_announcements_world_id");

                    b.ToTable("wild_rp_announcements", (string)null);
                });

            modelBuilder.Entity("MareSynchronosShared.Models.Auth", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "PrimaryUser")
                        .WithMany()
                        .HasForeignKey("PrimaryUserUID")
                        .HasConstraintName("fk_auth_users_primary_user_uid");

                    b.HasOne("MareSynchronosShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_users_user_uid");

                    b.Navigation("PrimaryUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.AutoDetectSchedule", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.Group", null)
                        .WithOne()
                        .HasForeignKey("MareSynchronosShared.Models.AutoDetectSchedule", "GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_autodetect_schedules_groups_group_gid");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaData", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_users_uploader_uid");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataAllowance", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.Group", "AllowedGroup")
                        .WithMany()
                        .HasForeignKey("AllowedGroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_chara_data_allowance_groups_allowed_group_gid");

                    b.HasOne("MareSynchronosShared.Models.User", "AllowedUser")
                        .WithMany()
                        .HasForeignKey("AllowedUserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_chara_data_allowance_users_allowed_user_uid");

                    b.HasOne("MareSynchronosShared.Models.CharaData", "Parent")
                        .WithMany("AllowedIndividiuals")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_allowance_chara_data_parent_id_parent_uploader_u");

                    b.Navigation("AllowedGroup");

                    b.Navigation("AllowedUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataFile", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.FileCache", "FileCache")
                        .WithMany()
                        .HasForeignKey("FileCacheHash")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_files_files_file_cache_hash");

                    b.HasOne("MareSynchronosShared.Models.CharaData", "Parent")
                        .WithMany("Files")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_files_chara_data_parent_id_parent_uploader_uid");

                    b.Navigation("FileCache");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataFileSwap", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.CharaData", "Parent")
                        .WithMany("FileSwaps")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_file_swaps_chara_data_parent_id_parent_uploader_");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataOriginalFile", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.CharaData", "Parent")
                        .WithMany("OriginalFiles")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_orig_files_chara_data_parent_id_parent_uploader_");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaDataPose", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.CharaData", "Parent")
                        .WithMany("Poses")
                        .HasForeignKey("ParentId", "ParentUploaderUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chara_data_poses_chara_data_parent_id_parent_uploader_uid");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharacterRpProfileData", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .HasConstraintName("fk_character_rp_profiles_users_user_uid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.ClientPair", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "OtherUser")
                        .WithMany()
                        .HasForeignKey("OtherUserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_pairs_users_other_user_uid");

                    b.HasOne("MareSynchronosShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_pairs_users_user_uid");

                    b.Navigation("OtherUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.Establishment", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.CharacterRpProfileData", "ManagerRpProfile")
                        .WithMany()
                        .HasForeignKey("ManagerRpProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_establishments_character_rp_profiles_manager_rp_profile_id");

                    b.HasOne("MareSynchronosShared.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_establishments_users_owner_uid");

                    b.Navigation("ManagerRpProfile");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.EstablishmentEvent", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.Establishment", "Establishment")
                        .WithMany("Events")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_establishment_events_establishments_establishment_id");

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.FileCache", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderUID")
                        .HasConstraintName("fk_file_caches_users_uploader_uid");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.Group", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUID")
                        .HasConstraintName("fk_groups_users_owner_uid");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.GroupBan", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "BannedBy")
                        .WithMany()
                        .HasForeignKey("BannedByUID")
                        .HasConstraintName("fk_group_bans_users_banned_by_uid");

                    b.HasOne("MareSynchronosShared.Models.User", "BannedUser")
                        .WithMany()
                        .HasForeignKey("BannedUserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_bans_users_banned_user_uid");

                    b.HasOne("MareSynchronosShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_bans_groups_group_gid");

                    b.Navigation("BannedBy");

                    b.Navigation("BannedUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.GroupPair", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_pairs_groups_group_gid");

                    b.HasOne("MareSynchronosShared.Models.User", "GroupUser")
                        .WithMany()
                        .HasForeignKey("GroupUserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_pairs_users_group_user_uid");

                    b.Navigation("Group");

                    b.Navigation("GroupUser");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.GroupProfile", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.Group", "Group")
                        .WithOne()
                        .HasForeignKey("MareSynchronosShared.Models.GroupProfile", "GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_profiles_groups_group_gid");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.GroupTempInvite", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_temp_invites_groups_group_gid");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.HousingShare", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_housing_shares_users_owner_uid");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.HousingShareAllowedGroup", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.HousingShare", "Share")
                        .WithMany("AllowedSyncshells")
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_housing_share_allowed_groups_housing_shares_share_id");

                    b.Navigation("Share");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.HousingShareAllowedUser", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.HousingShare", "Share")
                        .WithMany("AllowedIndividuals")
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_housing_share_allowed_users_housing_shares_share_id");

                    b.Navigation("Share");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.LodeStoneAuth", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .HasConstraintName("fk_lodestone_auth_users_user_uid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.McdfShare", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_mcdf_shares_users_owner_uid");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.McdfShareAllowedGroup", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.McdfShare", "Share")
                        .WithMany("AllowedSyncshells")
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mcdf_share_allowed_groups_mcdf_shares_share_id");

                    b.Navigation("Share");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.McdfShareAllowedUser", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.McdfShare", "Share")
                        .WithMany("AllowedIndividuals")
                        .HasForeignKey("ShareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mcdf_share_allowed_users_mcdf_shares_share_id");

                    b.Navigation("Share");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.Slot", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_slots_groups_group_gid");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.UserProfileData", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profile_data_users_user_uid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.UserProfileDataReport", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserUID")
                        .HasConstraintName("fk_user_profile_data_reports_users_reported_user_uid");

                    b.HasOne("MareSynchronosShared.Models.User", "ReportingUser")
                        .WithMany()
                        .HasForeignKey("ReportingUserUID")
                        .HasConstraintName("fk_user_profile_data_reports_users_reporting_user_uid");

                    b.Navigation("ReportedUser");

                    b.Navigation("ReportingUser");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.WildRpAnnouncement", b =>
                {
                    b.HasOne("MareSynchronosShared.Models.CharacterRpProfileData", "RpProfile")
                        .WithMany()
                        .HasForeignKey("RpProfileId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_wild_rp_announcements_character_rp_profiles_rp_profile_id");

                    b.HasOne("MareSynchronosShared.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("UserUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wild_rp_announcements_users_user_uid");

                    b.Navigation("Owner");

                    b.Navigation("RpProfile");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.CharaData", b =>
                {
                    b.Navigation("AllowedIndividiuals");

                    b.Navigation("FileSwaps");

                    b.Navigation("Files");

                    b.Navigation("OriginalFiles");

                    b.Navigation("Poses");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.Establishment", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.HousingShare", b =>
                {
                    b.Navigation("AllowedIndividuals");

                    b.Navigation("AllowedSyncshells");
                });

            modelBuilder.Entity("MareSynchronosShared.Models.McdfShare", b =>
                {
                    b.Navigation("AllowedIndividuals");

                    b.Navigation("AllowedSyncshells");
                });
#pragma warning restore 612, 618
        }
    }
}
